# Generated by Django 3.0.3 on 2021-01-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70, null=True)),
                ('lastname', models.CharField(max_length=70, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=70, null=True)),
                ('room', models.CharField(max_length=70, null=True)),
                ('subjects', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
