# Generated by Django 3.0.3 on 2021-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
